name: DNS Plan

# This workflow runs DNS planning when you're working on DNS changes
# It will show you what changes will be made before applying them

on:
  # Run on PRs that modify DNS workflows
  pull_request:
    paths:
      - '.github/workflows/dns-*.yml'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  plan:
    # Call the reusable workflow from vps-manager
    uses: ${{ vars.VPS_MANAGER_REPO || 'YOUR_GITHUB_USERNAME/vps-manager' }}/.github/workflows/dns-plan.yml@main
    with:
      # Update these values for your domain
      zone: myapp.example.com  # Your domain
      provider: cloudflare     # Your DNS provider (cloudflare, netlify, digitalocean, dnsimple, linode)
    secrets:
      # Make sure DNS_PROVIDER_TOKEN secret is set in your repo settings
      PROVIDER_TOKEN: ${{ secrets.DNS_PROVIDER_TOKEN }}
